export { default as ZjySidebar } from '@/views/index/sidebar'
export { default as ZjyHeader } from '@/views/index/header'
export { default as ZjyMain } from '@/views/index/Main'
export { default as ZjyBreadcrumb } from '@/components/breadcrumb/Breadcrumb'
export { default as NotFound } from '@/views/error/404'
export { default as NotAccessed } from '@/views/error/401'
